# tasks file for dhcpd
  - name: install dhcpd for ubuntu
    apt: 
      name: isc-dhcp-server
    when: ansible_distribution == "Ubuntu"

  - name: install dhcpd for centos
    dnf: 
      name: dhcp-server
    when: ansible_distribution == "CentOS"


