# tasks file for mariadb
- name: install mariadb on ubuntu
  apt:
    name: mariadb
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb on ubuntu
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"


