# tasks file for httpd
  - name: install apache for ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd for centos
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
