# tasks file for vsftpd
- name: install vsftpd on ubuntu
  apt:
    name: vsftpd
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install vsftpd on centos
  dnf:
    name: vsftpd
    state: latest
  when: ansible_distribution == "CentOS"


